spring.application.name=EcomJavaSpring

spring.datasource.url = jdbc:postgresql://localhost:5432/ecomproduct
spring.datasource.username = postgres
spring.datasource.password = Admin66@@55@@

spring.jpa.hibernate.ddl-auto=update



spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE